spring:
  application:
    name: investments-wallet
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        type: SYNC
        stdio: false
        name: investiments-wallet-mcp
        version: 1.0.0
  logging:
    level:
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      io.modelcontextprotocol: DEBUG
      org.springframework.ai.mcp: DEBUG

server:
  port: 8081

kind: Application